### ISSUE TITLE
ASCII Characters in XCode

### ISSUE THREAD

**Issue by rohanputcha** [FinalBlowup/Enigma#6]
Guys we need to fix this issue. The ASCII characters get outputted really well on my computer (CodeBlocks). But this won't work so easily on XCode because some characters are really bizarre (They actually look pretty cool, but strange). XCode just outputs a space which doesn't make any sense. This is pretty much the only issue that I have faced.
Look below at the picture of the ASCII characters and you can see for yourself how some are really peculiar. They look like tubes.
![ascii characters](https://cloud.githubusercontent.com/assets/23462896/20614329/e3732efc-b292-11e6-88f3-e5805dab2782.png)

**Comment by rohanputcha** [comment]
I've fixed this problem in b28995d. I made the number that changes the ascii characters a relatively smaller number and now it works on XCode.
 🎱

**Comment by AeolusDraco** [comment]
Also fixed in f306576.
